name: PR checks

on: 
  pull_request:
    branches:
        - develop
        - stage
        - main
    types: [opened, synchronize, reopened]

jobs:
    compliance:
        name: PR Compliance check
        runs-on: [self-hosted,Linux, cicdframework]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: ./.github/actions/sonarqube_scan
              name: Sonarqube-scan
              with:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


    Build_and_test_UI_code:
        runs-on: [self-hosted,Linux, cicdframework]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
             fetch-depth: 0
          - name: Set up Node.js 20.x
            uses: actions/setup-node@v4
            with:
             node-version: 20.x
        
          - name: Install dependencies
            run: npm install

          - name: Build
            run: npm run build 
            
          - name: Run the tests and generate coverage report
            run: npm test
